-- =====================================================
-- SBI SHED LOCO MANAGEMENT SYSTEM
-- DATABASE V1
-- =====================================================

-- ==========================================
-- DEPARTMENT MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS department_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_name VARCHAR(50) UNIQUE NOT NULL

);

-- ==========================================
-- SECTION MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS section_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_id BIGINT NOT NULL,

    section_name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_section UNIQUE(department_id, section_name),

    CONSTRAINT fk_section_department
    FOREIGN KEY(department_id)
    REFERENCES department_master(id)

);

-- ==========================================
-- DESIGNATION MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS designation_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_id BIGINT NOT NULL,

    designation_name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_designation
    UNIQUE(department_id, designation_name),

    CONSTRAINT fk_designation_department
    FOREIGN KEY(department_id)
    REFERENCES department_master(id)

);

-- ==========================================
-- EMPLOYEE MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS employees (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    mobile VARCHAR(20) UNIQUE NOT NULL,

    pf_no VARCHAR(30) UNIQUE NOT NULL,

    department_id BIGINT NOT NULL,

    section_id BIGINT NOT NULL,

    designation_id BIGINT NOT NULL,

    role VARCHAR(30) NOT NULL,

    status VARCHAR(20) DEFAULT 'Active',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_emp_department
    FOREIGN KEY(department_id)
    REFERENCES department_master(id),

    CONSTRAINT fk_emp_section
    FOREIGN KEY(section_id)
    REFERENCES section_master(id),

    CONSTRAINT fk_emp_designation
    FOREIGN KEY(designation_id)
    REFERENCES designation_master(id)

);

-- ==========================================
-- LOCO TYPE MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS loco_type_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    loco_type VARCHAR(30) UNIQUE NOT NULL

);

-- ==========================================
-- LOCO MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS loco_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    loco_no VARCHAR(20) UNIQUE NOT NULL,

    loco_type_id BIGINT NOT NULL,

    status VARCHAR(20) DEFAULT 'Active',

    CONSTRAINT fk_loco_type
    FOREIGN KEY(loco_type_id)
    REFERENCES loco_type_master(id)

);

-- ==========================================
-- SCHEDULE MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS schedule_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_id BIGINT NOT NULL,

    schedule_name VARCHAR(30) NOT NULL,

    CONSTRAINT uq_schedule
    UNIQUE(department_id, schedule_name),

    CONSTRAINT fk_schedule_department
    FOREIGN KEY(department_id)
    REFERENCES department_master(id)

);

-- ==========================================
-- WORK MASTER
-- ==========================================

CREATE TABLE IF NOT EXISTS work_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_id BIGINT NOT NULL,

    section_id BIGINT NOT NULL,

    schedule_id BIGINT NOT NULL,

    work_name TEXT NOT NULL,

    status VARCHAR(20) DEFAULT 'Active',

    CONSTRAINT fk_work_department
    FOREIGN KEY(department_id)
    REFERENCES department_master(id),

    CONSTRAINT fk_work_section
    FOREIGN KEY(section_id)
    REFERENCES section_master(id),

    CONSTRAINT fk_work_schedule
    FOREIGN KEY(schedule_id)
    REFERENCES schedule_master(id)

);

-- ==========================================
-- ASSIGN WORK HEADER
-- ==========================================

CREATE TABLE IF NOT EXISTS assign_work_header (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    assign_date DATE NOT NULL,

    loco_id BIGINT NOT NULL,

    schedule_id BIGINT NOT NULL,

    created_by BIGINT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_assign_loco
    FOREIGN KEY(loco_id)
    REFERENCES loco_master(id),

    CONSTRAINT fk_assign_schedule
    FOREIGN KEY(schedule_id)
    REFERENCES schedule_master(id),

    CONSTRAINT fk_assign_employee
    FOREIGN KEY(created_by)
    REFERENCES employees(id)

);

-- ==========================================
-- ASSIGN WORK DETAILS
-- ==========================================

CREATE TABLE IF NOT EXISTS assign_work_details (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    assign_header_id BIGINT NOT NULL,

    work_master_id BIGINT NOT NULL,

    supervisor_id BIGINT,

    status VARCHAR(20) DEFAULT 'Pending',

    remarks TEXT,

    CONSTRAINT fk_assign_header
    FOREIGN KEY(assign_header_id)
    REFERENCES assign_work_header(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_assign_work
    FOREIGN KEY(work_master_id)
    REFERENCES work_master(id),

    CONSTRAINT fk_assign_supervisor
    FOREIGN KEY(supervisor_id)
    REFERENCES employees(id)

);