-- ======================================================
-- SCHEDULE FORM MASTER
-- Stores one blank, versioned form template.
-- Complex EL/ML forms are stored in template_schema JSONB.
-- ======================================================

CREATE TABLE IF NOT EXISTS schedule_form_master (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    form_code VARCHAR(80) NOT NULL UNIQUE,
    form_name VARCHAR(200) NOT NULL,

    department VARCHAR(100) NOT NULL,
    section VARCHAR(100) NOT NULL,

    work_master_id BIGINT,
    schedule_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],

    source_file_name VARCHAR(255),

    template_schema JSONB NOT NULL DEFAULT
        '{"title":"","instructions":[],"columns":[],"rows":[]}'::JSONB,

    version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_schedule_form_master_work
        FOREIGN KEY (work_master_id)
        REFERENCES work_master(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_schedule_form_master_version
        CHECK (version > 0),

    CONSTRAINT chk_schedule_form_master_schema
        CHECK (jsonb_typeof(template_schema) = 'object')
);

-- Compatibility for a schedule_form_master table that was already
-- created as an empty/partial table in Supabase.
ALTER TABLE schedule_form_master
    ADD COLUMN IF NOT EXISTS form_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS form_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS department VARCHAR(100),
    ADD COLUMN IF NOT EXISTS section VARCHAR(100),
    ADD COLUMN IF NOT EXISTS work_master_id BIGINT,
    ADD COLUMN IF NOT EXISTS schedule_types TEXT[]
        DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN IF NOT EXISTS source_file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS template_schema JSONB
        DEFAULT '{"title":"","instructions":[],"columns":[],"rows":[]}'::JSONB,
    ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS
    uq_schedule_form_master_form_code
ON schedule_form_master (form_code)
WHERE form_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS
    idx_schedule_form_master_mapping
ON schedule_form_master (
    section,
    work_master_id,
    is_active
);


-- ======================================================
-- SCHEDULE FORM DETAILS
-- Stores the answers submitted for one manpower assignment.
-- One manpower distribution can submit one form.
-- ======================================================

CREATE TABLE IF NOT EXISTS schedule_form_details (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    schedule_form_master_id BIGINT NOT NULL,
    manpower_distribution_id BIGINT NOT NULL UNIQUE,
    staff_id BIGINT NOT NULL,

    template_version INTEGER NOT NULL,

    form_answers JSONB NOT NULL DEFAULT '{}'::JSONB,
    staff_remarks TEXT,

    status VARCHAR(30) NOT NULL DEFAULT 'Draft',

    submitted_at TIMESTAMPTZ,

    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    review_remarks TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_schedule_form_details_master
        FOREIGN KEY (schedule_form_master_id)
        REFERENCES schedule_form_master(id),

    CONSTRAINT fk_schedule_form_details_distribution
        FOREIGN KEY (manpower_distribution_id)
        REFERENCES manpower_distribution(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_schedule_form_details_staff
        FOREIGN KEY (staff_id)
        REFERENCES employee_master(id),

    CONSTRAINT fk_schedule_form_details_reviewer
        FOREIGN KEY (reviewed_by)
        REFERENCES supervisor_master(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_schedule_form_details_version
        CHECK (template_version > 0),

    CONSTRAINT chk_schedule_form_details_answers
        CHECK (jsonb_typeof(form_answers) = 'object'),

    CONSTRAINT chk_schedule_form_details_status
        CHECK (
            status IN (
                'Draft',
                'Submitted',
                'Under Review',
                'Returned',
                'Approved'
            )
        )
);

-- Compatibility for a schedule_form_details table that was already
-- created as an empty/partial table in Supabase.
ALTER TABLE schedule_form_details
    ADD COLUMN IF NOT EXISTS schedule_form_master_id BIGINT,
    ADD COLUMN IF NOT EXISTS manpower_distribution_id BIGINT,
    ADD COLUMN IF NOT EXISTS staff_id BIGINT,
    ADD COLUMN IF NOT EXISTS template_version INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS form_answers JSONB DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS staff_remarks TEXT,
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS reviewed_by BIGINT,
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS review_remarks TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS
    uq_schedule_form_details_distribution
ON schedule_form_details (manpower_distribution_id)
WHERE manpower_distribution_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS
    idx_schedule_form_details_staff_status
ON schedule_form_details (
    staff_id,
    status
);

CREATE INDEX IF NOT EXISTS
    idx_schedule_form_details_master
ON schedule_form_details (
    schedule_form_master_id
);


-- ======================================================
-- UPDATED-AT TRIGGER
-- ======================================================

CREATE OR REPLACE FUNCTION set_schedule_form_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS
    trg_schedule_form_master_updated_at
    ON schedule_form_master;

CREATE TRIGGER trg_schedule_form_master_updated_at
BEFORE UPDATE ON schedule_form_master
FOR EACH ROW
EXECUTE FUNCTION set_schedule_form_updated_at();

DROP TRIGGER IF EXISTS
    trg_schedule_form_details_updated_at
    ON schedule_form_details;

CREATE TRIGGER trg_schedule_form_details_updated_at
BEFORE UPDATE ON schedule_form_details
FOR EACH ROW
EXECUTE FUNCTION set_schedule_form_updated_at();


-- ======================================================
-- EXAMPLE BLANK TEMPLATE SHAPE
-- Do not insert this example as production data.
-- ======================================================

-- {
--   "title": "Auxiliary Machines Schedule",
--   "instructions": [],
--   "columns": [
--     {"key": "sn", "label": "S.No.", "type": "label"},
--     {"key": "activity", "label": "Detail of Work", "type": "label"},
--     {"key": "action_taken", "label": "Action Taken", "type": "text"},
--     {"key": "technician", "label": "Name of TCN", "type": "text"},
--     {"key": "remarks", "label": "Sign / Remarks", "type": "text"}
--   ],
--   "rows": [
--     {
--       "id": "A-1",
--       "sn": "1",
--       "activity": "Visually examine oil pumps for leakage."
--     }
--   ]
-- }
