-- External/out-of-course locos currently visiting the shed.
-- Their identity and assignment history remain separate from loco_master.

CREATE TABLE IF NOT EXISTS temporary_loco_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loco_no VARCHAR(20) UNIQUE NOT NULL,
    loco_type VARCHAR(30),
    last_position VARCHAR(80),
    tracking_status VARCHAR(30),
    is_in_shed BOOLEAN NOT NULL DEFAULT TRUE,
    tracking_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE assign_work_header
    ALTER COLUMN loco_id DROP NOT NULL;

ALTER TABLE assign_work_header
    ADD COLUMN IF NOT EXISTS temporary_loco_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_assign_temporary_loco'
    ) THEN
        ALTER TABLE assign_work_header
            ADD CONSTRAINT fk_assign_temporary_loco
            FOREIGN KEY (temporary_loco_id)
            REFERENCES temporary_loco_master(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_assign_one_loco_source'
    ) THEN
        ALTER TABLE assign_work_header
            ADD CONSTRAINT chk_assign_one_loco_source
            CHECK (num_nonnulls(loco_id, temporary_loco_id) = 1);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_assign_work_header_temporary_loco
    ON assign_work_header(temporary_loco_id);

