-- Pilot archive for old Electrical/Mechanical schedule PDFs.

CREATE TABLE IF NOT EXISTS historical_schedule_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loco_no VARCHAR(20) NOT NULL,
    department VARCHAR(30) NOT NULL,
    schedule_date DATE,
    schedule_type VARCHAR(50),
    original_filename TEXT NOT NULL,
    storage_path TEXT NOT NULL UNIQUE,
    file_size_bytes BIGINT NOT NULL,
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_historical_schedule_loco
    ON historical_schedule_records (loco_no, schedule_date DESC);

CREATE INDEX IF NOT EXISTS idx_historical_schedule_filters
    ON historical_schedule_records (department, schedule_type, schedule_date DESC);

ALTER TABLE historical_schedule_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS historical_schedule_read_pilot
    ON historical_schedule_records;
CREATE POLICY historical_schedule_read_pilot
    ON historical_schedule_records FOR SELECT
    TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS historical_schedule_import_pilot
    ON historical_schedule_records;
CREATE POLICY historical_schedule_import_pilot
    ON historical_schedule_records FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS historical_schedule_update_pilot
    ON historical_schedule_records;
CREATE POLICY historical_schedule_update_pilot
    ON historical_schedule_records FOR UPDATE
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'old-schedule-forms',
    'old-schedule-forms',
    false,
    52428800,
    ARRAY['application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS old_schedule_forms_read_pilot ON storage.objects;
CREATE POLICY old_schedule_forms_read_pilot
    ON storage.objects FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'old-schedule-forms');

DROP POLICY IF EXISTS old_schedule_forms_upload_pilot ON storage.objects;
CREATE POLICY old_schedule_forms_upload_pilot
    ON storage.objects FOR INSERT
    TO anon, authenticated
    WITH CHECK (bucket_id = 'old-schedule-forms');

DROP POLICY IF EXISTS old_schedule_forms_update_pilot ON storage.objects;
CREATE POLICY old_schedule_forms_update_pilot
    ON storage.objects FOR UPDATE
    TO anon, authenticated
    USING (bucket_id = 'old-schedule-forms')
    WITH CHECK (bucket_id = 'old-schedule-forms');

