-- Apply through the controlled database migration process before enabling demo controls.
CREATE TABLE IF NOT EXISTS demo_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    demo_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Ended')),
    started_by VARCHAR(100) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_by VARCHAR(100),
    ended_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_one_active_demo_session ON demo_sessions ((status)) WHERE status = 'Active';

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(100) NOT NULL,
    action VARCHAR(80) NOT NULL,
    demo_session_id UUID,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    result VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE demo_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_log ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON demo_sessions, admin_audit_log FROM anon, authenticated;
