CREATE TABLE IF NOT EXISTS temporary_staff_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL REFERENCES employee_master(id),
    loan_date DATE NOT NULL,
    department TEXT NOT NULL,
    from_section TEXT NOT NULL,
    to_section TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES supervisor_master(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT temporary_staff_loan_different_sections
        CHECK (LOWER(TRIM(from_section)) <> LOWER(TRIM(to_section))),
    CONSTRAINT uq_temporary_staff_loan_date
        UNIQUE (staff_id, loan_date)
);

CREATE INDEX IF NOT EXISTS idx_temporary_staff_loans_lookup
ON temporary_staff_loans (loan_date, department, from_section, to_section);
