CREATE TABLE IF NOT EXISTS incharge_charge_handover (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permanent_incharge_id BIGINT NOT NULL REFERENCES supervisor_master(id),
    acting_incharge_id BIGINT NOT NULL REFERENCES supervisor_master(id),
    department TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT charge_handover_different_people
        CHECK (permanent_incharge_id <> acting_incharge_id),
    CONSTRAINT charge_handover_valid_dates
        CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_charge_handover_active_dates
ON incharge_charge_handover (acting_incharge_id, start_date, end_date, status);

