-- Continuous/incomplete schedule-form workflow and dynamic Repairs work.
-- Run after database/14_repair_schedule_remarks.sql.
BEGIN;

ALTER TABLE schedule_form_details
    ADD COLUMN IF NOT EXISTS answer_attributions JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS completion_state VARCHAR(20) NOT NULL DEFAULT 'Incomplete',
    ADD COLUMN IF NOT EXISTS active_manpower_distribution_id BIGINT,
    ADD COLUMN IF NOT EXISTS original_manpower_distribution_id BIGINT,
    ADD COLUMN IF NOT EXISTS repair_loco_key VARCHAR(80);

UPDATE schedule_form_details
SET active_manpower_distribution_id = COALESCE(active_manpower_distribution_id, manpower_distribution_id),
    original_manpower_distribution_id = COALESCE(original_manpower_distribution_id, manpower_distribution_id)
WHERE active_manpower_distribution_id IS NULL OR original_manpower_distribution_id IS NULL;

-- Preserve already-running forms under the new status vocabulary.
UPDATE schedule_form_details
SET status='Submitted Complete', completion_state='Complete'
WHERE status='Submitted';
UPDATE schedule_form_details
SET completion_state='Complete'
WHERE status IN ('Supervisor Review','Forwarded to Incharge','Returned to Supervisor','Approved');

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_schedule_form_active_distribution') THEN
        ALTER TABLE schedule_form_details ADD CONSTRAINT fk_schedule_form_active_distribution
        FOREIGN KEY(active_manpower_distribution_id) REFERENCES manpower_distribution(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_schedule_form_original_distribution') THEN
        ALTER TABLE schedule_form_details ADD CONSTRAINT fk_schedule_form_original_distribution
        FOREIGN KEY(original_manpower_distribution_id) REFERENCES manpower_distribution(id) ON DELETE RESTRICT;
    END IF;
END $$;

ALTER TABLE schedule_form_details DROP CONSTRAINT IF EXISTS chk_schedule_form_details_status;
ALTER TABLE schedule_form_details ADD CONSTRAINT chk_schedule_form_details_status CHECK (status IN (
    'Draft','Submitted Incomplete','Supervisor Review','Returned to Staff',
    'Continuation Assigned','Submitted Complete','Forwarded to Incharge',
    'Returned to Supervisor','Approved'
));
ALTER TABLE schedule_form_details DROP CONSTRAINT IF EXISTS chk_schedule_form_completion_state;
ALTER TABLE schedule_form_details ADD CONSTRAINT chk_schedule_form_completion_state
    CHECK (completion_state IN ('Incomplete','Complete'));

CREATE TABLE IF NOT EXISTS schedule_form_continuations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_form_detail_id BIGINT NOT NULL REFERENCES schedule_form_details(id) ON DELETE RESTRICT,
    manpower_distribution_id BIGINT NOT NULL UNIQUE REFERENCES manpower_distribution(id) ON DELETE RESTRICT,
    staff_id BIGINT NOT NULL REFERENCES employee_master(id) ON DELETE RESTRICT,
    assigned_by BIGINT NOT NULL REFERENCES supervisor_master(id) ON DELETE RESTRICT,
    assigned_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_schedule_form_repair_loco
    ON schedule_form_details(repair_loco_key)
    WHERE repair_loco_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_schedule_form_continuations_form
    ON schedule_form_continuations(schedule_form_detail_id, created_at);

CREATE TABLE IF NOT EXISTS repair_schedule_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_schedule_remark_id BIGINT NOT NULL REFERENCES repair_schedule_remarks(id) ON DELETE RESTRICT,
    schedule_form_detail_id BIGINT REFERENCES schedule_form_details(id) ON DELETE RESTRICT,
    manpower_distribution_id BIGINT NOT NULL REFERENCES manpower_distribution(id) ON DELETE RESTRICT,
    staff_id BIGINT NOT NULL REFERENCES employee_master(id) ON DELETE RESTRICT,
    staff_name VARCHAR(150) NOT NULL,
    action_taken TEXT NOT NULL CHECK (btrim(action_taken) <> ''),
    status VARCHAR(30) NOT NULL DEFAULT 'Waiting for Incharge Approval'
        CHECK (status IN ('Waiting for Incharge Approval','Returned by Incharge','Completed')),
    reviewed_by BIGINT REFERENCES supervisor_master(id) ON DELETE RESTRICT,
    reviewed_at TIMESTAMPTZ,
    review_remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_repair_actions_remark
    ON repair_schedule_actions(repair_schedule_remark_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_repair_action_form_remark
    ON repair_schedule_actions(schedule_form_detail_id, repair_schedule_remark_id);

-- Add one active Repairs work to every existing schedule/section combination.
INSERT INTO work_master(department_id, section_id, schedule_id, work_name, status)
SELECT sm.department_id, sm.section_id, sm.id, 'Repairs', 'Active'
FROM schedule_master sm
WHERE sm.section_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM work_master wm
      WHERE wm.schedule_id=sm.id AND wm.section_id=sm.section_id
        AND lower(btrim(wm.work_name))='repairs'
  );

INSERT INTO schedule_form_master(
    form_code, form_name, department_id, section_id,
    department, section, loco_type, schedule_name, work_master_id,
    schedule_types, template_schema, version, is_active
)
SELECT 'REPAIRS-' || wm.id, 'Continuous Repair Schedule Form',
       wm.department_id, wm.section_id,
       dm.department_name, sec.section_name, 'Electric', sm.schedule_name, wm.id,
       ARRAY[sm.schedule_name]::TEXT[],
       jsonb_build_object('dynamic_type','repair_remarks','title','Repair Schedule Form'),
       1, TRUE
FROM work_master wm
JOIN schedule_master sm ON sm.id=wm.schedule_id
JOIN department_master dm ON dm.id=wm.department_id
JOIN section_master sec ON sec.id=wm.section_id
WHERE lower(btrim(wm.work_name))='repairs'
ON CONFLICT(form_code) WHERE form_code IS NOT NULL DO UPDATE SET
    work_master_id=EXCLUDED.work_master_id,
    schedule_types=EXCLUDED.schedule_types,
    template_schema=EXCLUDED.template_schema,
    is_active=TRUE;

CREATE OR REPLACE FUNCTION ensure_repairs_work_for_schedule()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE repairs_work_id BIGINT;
DECLARE department_name_value TEXT;
DECLARE section_name_value TEXT;
BEGIN
    IF NEW.section_id IS NULL THEN RETURN NEW; END IF;
    INSERT INTO work_master(department_id,section_id,schedule_id,work_name,status)
    SELECT NEW.department_id,NEW.section_id,NEW.id,'Repairs','Active'
    WHERE NOT EXISTS (
        SELECT 1 FROM work_master WHERE schedule_id=NEW.id AND section_id=NEW.section_id
          AND lower(btrim(work_name))='repairs'
    );
    SELECT id INTO repairs_work_id FROM work_master
    WHERE schedule_id=NEW.id AND section_id=NEW.section_id AND lower(btrim(work_name))='repairs' LIMIT 1;
    SELECT department_name INTO department_name_value FROM department_master WHERE id=NEW.department_id;
    SELECT section_name INTO section_name_value FROM section_master WHERE id=NEW.section_id;
    INSERT INTO schedule_form_master(
        form_code,form_name,department_id,section_id,department,section,
        loco_type,schedule_name,work_master_id,schedule_types,template_schema,version,is_active
    )
    VALUES('REPAIRS-'||repairs_work_id,'Continuous Repair Schedule Form',NEW.department_id,NEW.section_id,
           department_name_value,section_name_value,'Electric',NEW.schedule_name,
           repairs_work_id,ARRAY[NEW.schedule_name]::TEXT[],jsonb_build_object('dynamic_type','repair_remarks','title','Repair Schedule Form'),1,TRUE)
    ON CONFLICT(form_code) WHERE form_code IS NOT NULL DO NOTHING;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_schedule_ensure_repairs_work ON schedule_master;
CREATE TRIGGER trg_schedule_ensure_repairs_work
AFTER INSERT OR UPDATE OF section_id,schedule_name ON schedule_master
FOR EACH ROW EXECUTE FUNCTION ensure_repairs_work_for_schedule();

COMMIT;
