-- Review before running. This migration does not modify submitted schedule forms.
CREATE TABLE IF NOT EXISTS schedule_form_template_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_form_master_id BIGINT NOT NULL REFERENCES schedule_form_master(id),
    version INTEGER NOT NULL CHECK (version > 0),
    template_schema JSONB NOT NULL CHECK (jsonb_typeof(template_schema) = 'object'),
    edited_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (schedule_form_master_id, version)
);

CREATE INDEX IF NOT EXISTS idx_schedule_form_template_versions_master
ON schedule_form_template_versions(schedule_form_master_id, version DESC);

CREATE OR REPLACE FUNCTION save_schedule_form_template_version(
    p_template_id BIGINT,
    p_document_html TEXT,
    p_editor TEXT
) RETURNS TABLE(template_id BIGINT, new_version INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    current_template schedule_form_master%ROWTYPE;
    next_version INTEGER;
    next_schema JSONB;
BEGIN
    SELECT * INTO current_template
    FROM schedule_form_master
    WHERE id = p_template_id
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'Schedule form template not found'; END IF;
    IF length(trim(COALESCE(p_document_html, ''))) < 20 THEN
        RAISE EXCEPTION 'Template HTML is empty or invalid';
    END IF;

    INSERT INTO schedule_form_template_versions(
        schedule_form_master_id, version, template_schema, edited_by
    ) VALUES (
        current_template.id, current_template.version,
        current_template.template_schema, p_editor
    ) ON CONFLICT(schedule_form_master_id, version) DO NOTHING;

    next_version := current_template.version + 1;
    next_schema := jsonb_set(
        COALESCE(current_template.template_schema, '{}'::jsonb),
        '{document_html}', to_jsonb(p_document_html), true
    );

    INSERT INTO schedule_form_template_versions(
        schedule_form_master_id, version, template_schema, edited_by
    ) VALUES (current_template.id, next_version, next_schema, p_editor);

    UPDATE schedule_form_master
    SET template_schema = next_schema, version = next_version
    WHERE id = current_template.id;

    RETURN QUERY SELECT current_template.id, next_version;
END;
$$;

REVOKE ALL ON FUNCTION save_schedule_form_template_version(BIGINT, TEXT, TEXT) FROM PUBLIC;
