-- Approved schedule-form persistence split.
-- Full approved form snapshots go to Storage; searchable measurements,
-- exceptions, actions and remarks remain as structured database rows.
BEGIN;

ALTER TABLE schedule_form_details
    ADD COLUMN IF NOT EXISTS field_metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS archive_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS archive_format VARCHAR(40),
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS schedule_form_search_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_form_detail_id BIGINT NOT NULL
        REFERENCES schedule_form_details(id) ON DELETE CASCADE,
    schedule_form_master_id BIGINT NOT NULL
        REFERENCES schedule_form_master(id) ON DELETE RESTRICT,
    loco_no VARCHAR(30) NOT NULL,
    schedule_name VARCHAR(120) NOT NULL,
    schedule_date DATE,
    department VARCHAR(100),
    section VARCHAR(100),
    answer_key TEXT NOT NULL,
    parameter_name TEXT NOT NULL,
    section_name TEXT,
    field_kind VARCHAR(40) NOT NULL,
    retention_reason VARCHAR(40) NOT NULL,
    text_value TEXT NOT NULL,
    numeric_value NUMERIC,
    unit VARCHAR(40),
    standard_value TEXT,
    validation_state VARCHAR(30),
    answer_attribution JSONB NOT NULL DEFAULT '{}'::JSONB,
    field_metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    approved_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(schedule_form_detail_id, answer_key)
);

CREATE INDEX IF NOT EXISTS idx_schedule_search_loco_schedule_date
    ON schedule_form_search_values(loco_no, schedule_name, schedule_date DESC);
CREATE INDEX IF NOT EXISTS idx_schedule_search_parameter
    ON schedule_form_search_values(parameter_name);
CREATE INDEX IF NOT EXISTS idx_schedule_search_numeric
    ON schedule_form_search_values(numeric_value)
    WHERE numeric_value IS NOT NULL;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'approved-schedule-forms',
    'approved-schedule-forms',
    false,
    52428800,
    ARRAY['application/json']
)
ON CONFLICT (id) DO UPDATE SET
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS approved_schedule_forms_read ON storage.objects;
CREATE POLICY approved_schedule_forms_read
    ON storage.objects FOR SELECT TO anon, authenticated
    USING (bucket_id = 'approved-schedule-forms');
DROP POLICY IF EXISTS approved_schedule_forms_upload ON storage.objects;
CREATE POLICY approved_schedule_forms_upload
    ON storage.objects FOR INSERT TO anon, authenticated
    WITH CHECK (bucket_id = 'approved-schedule-forms');
DROP POLICY IF EXISTS approved_schedule_forms_update ON storage.objects;
CREATE POLICY approved_schedule_forms_update
    ON storage.objects FOR UPDATE TO anon, authenticated
    USING (bucket_id = 'approved-schedule-forms')
    WITH CHECK (bucket_id = 'approved-schedule-forms');

COMMIT;
